### ISSUE TITLE
Incorrect Response Options

### ISSUE THREAD

**Issue by kevinmoran805** [MD2Korg/mCerebrum-EMA#1]
Under the 'End of Day' EMA, the question is asked

> How strong is your urge to smoke right now?

The response options listed are

> NO!!! NO no yes YES YESS!!!

The responses should either be
> "No Urge, Week, Moderate, Strong, Severe" 

or we should change the question to read

>"In the last ten minutes, have you had a strong temptation/urge to smoke?"

I've contacted Bonnie for a final decision and will update here when I have it. If we change the question, it should also apply to the random and event-contingent EMA questions.

**Comment by kevinmoran805** [comment]
We will use this wording for the 'Urge' question from now on:

> In the last ten minutes, have you had a strong temptation/urge to smoke?

The responses will match the other stress questions:

> NO!!! NO no yes YES YESS!!!

I have changed this in the EMA document on google drive as well:
https://docs.google.com/document/d/1VJAIa8-FxX5CCiMXyZxUBbsg86XrO09_G4vYOP4XPJo/edit

This change should be reflected everywhere this question is asked: the event-contingent, random, and end of day EMAs.

**Comment by twhnat** [comment]
@monowar Is this fixed in the latest version of the configuration?

**Comment by monowar** [comment]
fixed in the latest version of configuration
