### ISSUE TITLE
Additional Context Questions

### ISSUE THREAD

**Issue by kevinmoran805** [MD2Korg/mCerebrum-EMA#2]
As per the EMA doc on google drive, please add these these questions to be asked the Stress questions during random and event-contingent EMAs:

Variable name: Cue1
>Do you see someone smoking or do you smell cigarettes?
(0=no; 1=yes)

Variable name: Cue2
> Do you have access to cigarettes right now?
> (0=no; 1=yes)

Variable name: Cue3
> Are you someplace where you can smoke?
> (0=no; 1=yes)

**Comment by twhnat** [comment]
@monowar Has this been incorporated in the latest version of the configurations

**Comment by monowar** [comment]
incorporated
