### ISSUE TITLE
Event EMA condition

### ISSUE THREAD

**Issue by keitokawabata** [MD2Korg/mCerebrum-EMA#3]
EMA 0.2.0

Event Contingent Recording

1. "I puffed" response NO
2. "Approximately how long ago did you take the first puff from that cigarette?" 

Might be a issue with the conditions. If someone said NO on the first question, the EMA shouldn't ask how long ago was did you take the first puff from that cigarette.

**Comment by twhnat** [comment]
Issue moved to [MD2Korg/configurations #1](https://github.com/MD2Korg/configurations/issues/1) via [**ZenHub.io**](https://www.zenhub.io/)
