### ISSUE TITLE
EMA Question Issues

### ISSUE THREAD

**Issue by DanielaGarza** [MD2Korg/mCerebrum-EMA#4]
Date: 4/4/2016
Time: 12:30 PM
-	(J) On the alcohol question, you can select BOTH “did not drink” and “beer” or “wine” etc
-	(M) On the smoking question, I reported that I did not smoke and the next question asked me how   long ago I smoked
-	(M-2) On the question that asks “how many cigarettes did you smoke?”, the response says “ ___________ minutes” instead of “________ cigarettes”. When you type in a response, it does not allow you to advance to the next question. The NEXT button is grayed out.
-	It allowed me to take more than 1 smoking survey in the same block.
              o	The second survey I took ended before it got to the end and went straight to the payment screen. Payment calculation was the same as below.

**Comment by monowar** [comment]
issue resolved in EMA version 0.2.3
