### ISSUE TITLE
EMA Restricted Access

### ISSUE THREAD

**Issue by DanielaGarza** [MD2Korg/mCerebrum-EMA#5]
Date: 4/4/2016
Time: 1:30 PM
Phone: DG2
Self reported smoking event which prompted EMA. Clicked "Ok" then got a notification that said "Your IT Admin has restricted access to the app - EMA" and was not allowed to complete assessment.

This phone is the only one that has the AirWatch app running at all times (I didn't know how to turn it off/on).

**Comment by twhnat** [comment]
We are scheduled to test AirWatch today.  Please use the other phones for the time being and Shahin will be in touch after the testing.

**Comment by twhnat** [comment]
Resolved by adding all applications to Air Watch
