### ISSUE TITLE
EMA Question Issues

### ISSUE THREAD

**Issue by DanielaGarza** [MD2Korg/mCerebrum-EMA#6]
(J) Are other people smoking around you? - If participants click "No one around me is smoking" they should not be allowed to click any of the other options. 

(N) (O) For both the stressor and positive experience questions that start with: Since the last assessment, did you experience or think about... - If participants click "not applicable to me" they should not be allowed to click on any of the other options. 

(L) (M1) (M2) For the questions that involve scrolling to see all the options (e.g., Discrimination, when did you smoke the first cig, when did you smoke the most recent cig), we should tell participants to scroll down for more options

**Comment by DanielaGarza** [comment]
On the alcohol question, you can select BOTH “did not drink” and “beer” or “wine” etc

**Comment by monowar** [comment]
@DanielaGarza It is handled in the new version of the software. Please check it.
